hangman/config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  resources :games, only: [:new, :index, :show, :create, :destroy] do
    resources :letters, only: [:index, :create]
  end
end

hangman/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

hangman/app/models/game.rb
class Game < ApplicationRecord
  MASK_CHAR = "\0".freeze
  MAX_FAILS = 6

  has_many :letters, dependent: :destroy

  validates_format_of :word, with: /\A[a-z]+\z/
  # validate my_custom_stuff

  after_initialize do
    self.word = random_word if word.blank?
  end

  def name
    return "Game #{id}" if read_attribute(:name).blank?
    read_attribute(:name)
  end

  def masked_word
    tried_letters = self.tried_letters
    word.chars.reduce('') do |masked, letter|
      masked += tried_letters.include?(letter) ? letter.upcase : MASK_CHAR
    end
  end

  def status
    result || 'Playing'
  end

  def playing?
    !result
  end

  def failed_letters
    tried_letters.select{ |letter| ! word.include? letter }
  end

  def tried_letters
      letters.all.map{ |element| element.value }
  end

  def result
    return 'Won' unless masked_word.include? MASK_CHAR
    return 'Lost' if failed_letters.length >= MAX_FAILS
  end

  private

  def random_word
    File.readlines('app/models/words.txt').sample.chomp
  end
end

hangman/app/models/letter.rb
class Letter < ApplicationRecord
  belongs_to :game
  validates_length_of :value, is: 1
  validates_format_of :value, with: /\A[a-z]\z/
  validates_uniqueness_of :value, scope: :game_id
end

hangman/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

hangman/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :find_game, only: [:show, :destroy]

  def index
    @games = Game.all
  end

  def destroy
    @game.destroy
    redirect_to games_path
  end

  def create
    @game = Game.new(
      'name' => params[:game]['name'],
      'word' => params[:game]['word'],
    )
    @game.save
    redirect_to game_path(@game)
  end

  private

  def find_game
    @game = Game.find(params[:id])
  end
end

hangman/app/controllers/letters_controller.rb
class LettersController < ApplicationController
  def create
    @game = Game.find(params[:game_id])
    @letter = @game.letters.create(value: params[:letter])
    @letter.save
    redirect_to game_path(@game)
  end
end

hangman/app/helpers/application_helper.rb
module ApplicationHelper
end

hangman/app/helpers/games_helper.rb
module GamesHelper
  def secret_word(game)
    game.playing? ? game.masked_word.gsub(/\0/, "\u200A_\u200A") : game.word.upcase
  end

  def failed_letters(game)
    game.failed_letters.join(', ').upcase
  end

end

hangman/app/views/games/_gallows.html.erb
<tt>
<% if @game.failed_letters.length == 0 %>
  &nbsp;&nbsp;&nbsp;+--+<br>
  &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;=======<br>
<% elsif @game.failed_letters.length == 1%>
  &nbsp;&nbsp;&nbsp;+--+<br>
  &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;O&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;=======<br>
<% elsif @game.failed_letters.length == 2%>
  &nbsp;&nbsp;&nbsp;+--+<br>
  &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;O&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;=======<br>
<% elsif @game.failed_letters.length == 3%>
  &nbsp;&nbsp;&nbsp;+--+<br>
  &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;O&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;/|&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;=======<br>
<% elsif @game.failed_letters.length == 4%>
  &nbsp;&nbsp;&nbsp;+--+<br>
  &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;O&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;/|\&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;=======<br>
<% elsif @game.failed_letters.length == 5%>
  &nbsp;&nbsp;&nbsp;+--+<br>
  &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;O&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;/|\&nbsp;|<br>
  &nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;=======<br>
<% else %>
  &nbsp;&nbsp;&nbsp;+--+<br>
  &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;O&nbsp;&nbsp;|<br>
  &nbsp;&nbsp;/|\&nbsp;|<br>
  &nbsp;&nbsp;/&nbsp;\&nbsp;|<br>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;|<br>
  &nbsp;=======<br>
<% end %>
</tt>

hangman/app/views/games/_state.html.erb
<h1>
  <%= @game.status.capitalize + ' ' + @game.name %>
</h1>

<p>
<%= render 'gallows' %>
</p>

<p>
  <strong>Word:</strong>
  <%= secret_word(@game) %></td>
</p>

<p>
  <strong>Failed letters:</strong>
  <%= failed_letters(@game) %>
</p>

hangman/app/views/games/index.html.erb
<h1>Super Hangman</h1>
<p><b><%= link_to 'New game', new_game_path %></b></p>

<table>
  <tr>
    <th>Name</th>
    <th>Word</th>
    <th>Status</th>
    <th colspan="2"></th>
  </tr>

  <% @games.each do |game| %>
    <tr>
      <td><%= game.name %></td>
      <td><%= game.playing? ? game.masked_word.gsub(/\0/, "\u200A_\u200A") : game.word.upcase %></td>
      <td><%= game.status %></td>
      <td>
      <% if game.playing? %>
        <%= link_to 'Play', game_path(game) %>
      <% else %>
        <%= link_to 'Show', game_path(game) %>
      <% end %>
      </td>
      <td><%= link_to 'Clear', game_path(game), method: :delete %></td>
    </tr>
  <% end %>
</table>

hangman/app/views/games/new.html.erb
<h1>New Game</h1>
<p>Some extra game parameters might be here</p>

<%= form_for :game, url: games_path do |f| %>
  <p>
    <%= f.label :name, 'Name (you may leave it empty)' %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :word, 'Word (you may leave it empty)' %><br>
    <%= f.text_field :word %>
  </p>

  <p>
    <%= f.submit "Start Game"%>
  </p>
<% end %>

<%= link_to 'Back', games_path %>

hangman/app/views/games/show.html.erb
<%= render 'state' %>
<% if @game.playing? %>
  <p>
    <% (('a'..'z').to_a - @game.tried_letters).each do |letter| %>
      <%= link_to letter.upcase, game_letters_path(@game, 'letter' => letter), method: :post %>
    <% end %>
  </p>
<% end %>
<%= link_to 'Back', games_path %>

hangman/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hangman</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>